###
### Page Settings
###

title: Bruno Henriques | Backend Dev
url: "http://bphenriques.github.io"


###
### Build settings
###

compress_html:
  clippings: all
  comments: all
  blanklines: false

# Handling Reading
exclude: ["README.md"]

sass:
  clippings: all
  style: compressed
